{
  "name": "network.networkmanager",
  "kind": "config",
  "provides": {"state_fragments": ["network"]},
  "dependencies": [],
  "entrypoint": "twin_core.plugins_runtime.network_networkmanager:NetworkManagerPlugin"
}
name: "network.networkmanager"
kind: "config"
provides:
  state_fragments:
    - "network"
dependencies: []
entrypoint: "twin_core.plugins_runtime.network_networkmanager:NetworkManagerPlugin"
